language: python
python: "3.5"
# command to install dependencies
install: pip install '-U --upgrade-strategy=eager Nikola==8.0.0b2' requests PyYAML webassets
# command to run tests
script:
  - mkdir -p posts/directory && rm -f posts/directory/*
  - ./import_rss.py
  - nikola build
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  virtualenv -p python2.7 /tmp/venv &&
  . /tmp/venv/bin/activate &&
  pip install ghp-import &&
  ghp-import -n output &&
  git push -qf https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
notifications:
  email:
    recipients:
      - secure: "ueb9lK3F7jz8y7pzm/uyFfCx2otI5COwneiY7AXqbDZU3+6FDdCInKGtD3qriW+QwbhRo8EYpux7v6VT1m6F9YKQ4BC2+SWS2UfmBEql1PoCrXkP0sc86ZoisQ3bOBIS/YyVrOsGSHhjXPz/T3rQ9Bqqgp78SxWTygJ3IaGl7fTcmyFYSP4Xy8NPhT7pCMBa/mM62mpkTihsmvzHr+5dePdvvUc0Rnhh9NgDaggGW6RqRKifR2jV3WFxKOdv45YCIlAd59cd3xCuaRbjtbcSREn7YoLQCc4TCb8saCigFe9SqXx75TIpMhjdXYHPCFO9F47g8I0DIUkUkowBmYuaJFinrcJ+gDoODe7aYHrxp5db5l5GcsV4U4jP/ulpOG/r00VHjmtrGx9dagHm1KtD50lX/g9Y/fNyavtpv4lQMnLi3me5XnF40yJ4CGMsaxoqYvOAi34hBaqtHhqew0On9uQpU2g7PEZALLg1m0/0QGYlT0vVaA5TlmhZtZonznMuxp/eIH2bjBWOZ4hMCJPoPJnu2y2luDXPh8fTCemGgCZ6B4HHRpPqozqh/bdHKH9GtVqURbrgL/x11b0/ydQZprazspFh0cz79uoairIVeukTdjBLdFGWRapYASW/6gKNlcHhVe/U1fRgSgEBcoBThqEkCbo5pe7dUE5h0LeIjXE="
      - secure: "FdPnJN/kljps4uWZtXiTF8EixrZ67FL/5jRHzch55FMt241ClRxrxCBwSUFQJmryUCVnf1ELcLjxzjFdvjiMG5t+egeclV3vW1aeSSv30kqvxOEdu6KjX7Ayh2F88db94xrH6LM+eeWgWYYEWNU9ftqdQW0iHCYvKRv3SB8wbODFDSAZpOP/oDoVHHzpxTFrXXZaq73JAtCIRhbRX4sXhoGzaYk+W4unOeeLAY07EbmiQLRdiXxPPMBbj1w4pfjbDM9Gk2YHTAlkGnNqUFHZ9/q8S7WmJ4fpUMDTSR5gzZ8Ggi/IV21vq8DJ9wkaBibPktI9+vzH43RcgRax9Xiv+BIUpxPeUkHrf0G7jhroEI0BBkKfL/hiPlk6QiV5G6exQy9Usqw7FhLvwLSglvdZ7Hk1GnI0YK1+d2QL4scU36lbK4dxBEwm/KRQgVNCXEeth9BoyQUiFUCiZ+OWkhb/7cfLEeBv8OnCFFDQ2+W/EeCovzMaasKLmsOxP8XwK4s13qNkZWXUepcUnEAsNA2oNSZhJULOIZw08/Zq2qLJJKg0o93FG7KO1Oc9qrydDR/9akN5DSRtl3KpqyjTj8GwwOKKfD2k9ej8MGj6VZQFSugEIqEsagnsfIQyFxOpx+CvaOBw11VK9KGtcy1DuQoUJkkafGH7UxbRCsPOfSf7gUM="
    on_success: change
    on_failure: always
